version: '3'

networks:

  fabric: {}

services:

  clock:

    build: ./clock
    networks:
      - fabric
    ports:
      - 4567:4567

  sidecar:

    build: ./sidecar
    networks:
      - fabric
    ports:
      - 7080:7080
      - 7081:7081

  edge:

    build: ./edge
    networks:
      - fabric
    ports:
      - 8080:8080
      - 8081:8081

  statsd:

    image: prom/statsd-exporter:v0.4.0
    command: "/bin/statsd_exporter -log.level=debug"
    networks:
      - fabric
    ports:
      - 9102:9102
      - 9125:9125

  zipkin:

    image: openzipkin/zipkin:1.28.1
    networks:
      - fabric
    ports:
      - 9411:9411
